name: Check commit

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    check-commit:
        name: Commit standard
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code (full-history)
              if: github.event_name == 'pull_request'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Checkout code
              if: github.event_name == 'push'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun ci

            - name: Check current commit
              if: github.event_name == 'push'
              run: bunx commitlint --last --verbose

            - name: Check PR commits
              if: github.event_name == 'pull_request'
              run: npx bunx --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
