name: CI

on: [push, pull_request]

jobs:
    code-quality:
        name: Check format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun ci

            - name: Run formatter & linter
              run: bunx biome ci . --reporter=github

    type:
        name: Check type
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun ci

            - name: Run check
              run: bun check:type

    spec:
        name: Check spec
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun ci

            - name: Run check
              run: bun check:spec

            - name: Upload lcov.info
              uses: actions/upload-artifact@v4
              with:
                  name: lcov-${{ matrix.os }}
                  path: coverage/lcov.info
                  if-no-files-found: error
                  overwrite: true

            - name: Upload junit.xml
              uses: actions/upload-artifact@v4
              with:
                  name: junit-${{ matrix.os }}
                  path: junit.xml
                  if-no-files-found: error
                  overwrite: true

    codecov:
        needs: spec
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download lcov.info
              uses: actions/download-artifact@v4
              with:
                  name: lcov-${{ matrix.os }}

            - name: Upload lcov.info
              uses: codecov/codecov-action@v5
              with:
                  fail_ci_if_error: true
                  verbose: true
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Upload junit.xml
              uses: codecov/test-results-action@v1
              with:
                  fail_ci_if_error: true
                  verbose: true
                  token: ${{ secrets.CODECOV_TOKEN }}
