name: Dependabot Pull Request

on:
    pull_request:
        paths:
            - package.json
            - yarn.lock

jobs:
    main:
        name: Update lockfile
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Update lockfile
              run: bun install --yarn

            - name: Update PR
              run: |
                  git add bun.lockb yarn.lock
                  git config --global user.name github-actions
                  git config --global user.email github-actions@github.com
                  git commit -n --amend
                  git push --force-with-lease
