name: Dependabot Pull Request

on:
    pull_request:
        paths:
            - "package.json"
            - "yarn.lock"

permissions:
    contents: write

jobs:
    main:
        name: Update lockfile
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Update lockfile
              run: bun install --yarn

            - name: Update PR
              run: |
                  git add bun.lockb yarn.lock
                  git config user.name "dependabot[bot]"
                  git config user.email "dependabot[bot]@users.noreply.github.com"
                  git commit --amend --no-edit
                  git push --force-with-lease
