name: Dependabot PR

run-name: Dependabot PR > ${{ github.event.pull_request.title }}

on:
    pull_request:
        branches:
            - main
        paths:
            - package.json
            - yarn.lock

jobs:
    update-lockfile:
        name: Update lockfile
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2

            - name: Update lockfile
              run: bun install --yarn

            - name: Update PR
              run: |
                  git add bun.lockb yarn.lock
                  git commit --amend --no-edit --no-verify
                  git push --force-with-lease --no-verify
