name: reviewdog
on: [pull_request]
jobs:
    code-quality:
        name: Check code quality
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Review code
              uses: mongolyy/reviewdog-action-biome@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review
                  fail_on_error: true
